### ISSUE TITLE
Support for CIDv1

### ISSUE THREAD

**Issue by lidel** [ipfs/is-ipfs#12]
As noted in https://github.com/ipfs/ipfs-companion/issues/275,  `is-ipfs` v0.3.0 is unaware of [CIDv1](https://github.com/ipld/cid#cidv1).

References:

- Spec: https://github.com/ipld/cid
- JS implementation: https://github.com/ipld/js-cid

**Comment by diasdavid** [comment]
@fbaiodias wanna move this to the IPFS org so that more folks can help maintain it?

**Comment by fbaiodias** [comment]
@diasdavid done https://github.com/ipfs/is-ipfs/ 😃

**Comment by lidel** [comment]
Guys, please check if #13 looks okay.
If it does, we need a new release of `is-ipfs` 🌵
