### ISSUE TITLE
Should be part of the IPFS org + needs a Lead Maintainer + needs to have Jenkins run.

### ISSUE THREAD

**Issue by diasdavid** [ipfs/is-ipfs#17]

**Comment by diasdavid** [comment]
@lidel are you the lead maintainer for this module?

**Comment by lidel** [comment]
I can be, but need npm rights :)

**Comment by diasdavid** [comment]
you got it! :)

**Comment by lidel** [comment]
@diasdavid can I get admin right to this repo as well? (want to check if Jenkins integration has proper rights etc)
