### ISSUE TITLE
Multiaddress checking support

### ISSUE THREAD

**Issue by obo20** [ipfs/is-ipfs#26]
Would it be possible to get support for checking a valid multiaddress? I want to validate peer multiaddresses being passed into our API before attempting to connect to them via "ipfs swarm connect"

**Comment by lidel** [comment]
@obo20 care to elaborate? any thoughts on how it should work? 

Should it just check if it is a valid multiaddr in general, 
or do you want to ensure it is a valid ipfs peer multiaddr ? (or both)

----

Quick notes:

Basic validation could be done via:

```js
const Multiaddr = require('multiaddr')
function isMultiaddr (input) {
  try {
    new Multiaddr(input)
    return true
  } catch (e) {
    return false
  }
}
```

With the above, the public check API would work like this:

```js
isIPFS.multiaddr('/ip4/127.0.0.1/udp/1234') // true
isIPFS.multiaddr('/ip4/127.0.0.1/udp/1234/http') // true
isIPFS.multiaddr('/ip6/::1/udp/1234') // true
isIPFS.multiaddr('/yoloinvalid/::1/udp/1234') // false
```

For checking if multiaddr is of a specific type, the [mafmt](https://www.npmjs.com/package/mafmt) API  can be used. 
We could add a peer multiaddr check to `is-ipfs` like this:

```js
const mafmt = require('msfmt')
function isPeerMultiaddr (input) {
  return isMultiaddr (input) && mafmt.IPFS.matches(input)
}
```

```js
isIPFS.peerMultiaddr('/ipfs/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSoooo4') // true                                                                                                                                                                                      
isIPFS.peerMultiaddr('/ip4/127.0.0.1/tcp/1234/ws/ipfs/QmUjNmr8TgJCn1Ao7DvMy4cjoZU15b9bwSCBLE3vwXiwgj') // true
isIPFS.peerMultiaddr('/ipfs/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSoooo4/p2p-circuit/ipfs/QmUjNmr8TgJCn1Ao7DvMy4cjoZU15b9bwSCBLE3vwXiwgj') // true
isIPFS.peerMultiaddr('/ip4/127.0.0.1/udp/1234') // false
```

cc @hacdias @olizilla – Thoughts? I imagine `peerMultiaddr` would be useful in the context of https://github.com/ipfs-shipyard/ipfs-webui/pull/969

**Comment by hacdias** [comment]
@lidel yes, I believe it would be useful on that case (Web UI). We could build the functions dynamically from `maft.${STH}` --> `isSthMultiaddr`.

**Comment by obo20** [comment]
@lidel I was specifically referring to the valid peer multi-address checking, although I'm sure some people might find the normal multiaddr checking useful as well.

The examples you provided for each option seem perfect to me!
